#####################################################################
#### Please don't change this file. Use component.mk instead ####
#####################################################################

ifndef SMING_HOME
$(error SMING_HOME is not set: please configure it as an environment variable)
endif

# This is Host build only
override SMING_ARCH := Host

include $(SMING_HOME)/project.mk
