/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "hosted.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RequestDigitalWrite, RequestDigitalWrite, AUTO)


PB_BIND(RequestPinMode, RequestPinMode, AUTO)


PB_BIND(RequestDigitalRead, RequestDigitalRead, AUTO)


PB_BIND(ResponseDigitalRead, ResponseDigitalRead, AUTO)


PB_BIND(HostedCommand, HostedCommand, AUTO)





