/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_HOSTED_PB_H_INCLUDED
#define PB_HOSTED_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _PinMode { PinMode_INPUT = 0, PinMode_OUTPUT = 1, PinMode_INPUT_PULLUP = 2 } PinMode;

typedef enum _SpiSettings_ByteOrder {
	SpiSettings_ByteOrder_MSBFIRST = 0,
	SpiSettings_ByteOrder_LSBFIRST = 1
} SpiSettings_ByteOrder;

typedef enum _SpiSettings_DataMode {
	SpiSettings_DataMode_SPI_MODE0 = 0,
	SpiSettings_DataMode_SPI_MODE1 = 1,
	SpiSettings_DataMode_SPI_MODE2 = 2,
	SpiSettings_DataMode_SPI_MODE3 = 3
} SpiSettings_DataMode;

typedef enum _HostedCommand_Version { HostedCommand_Version_HOSTED_V_1_0 = 0 } HostedCommand_Version;

/* Struct definitions */
typedef struct _RequestSpiEndTransaction {
	char dummy_field;
} RequestSpiEndTransaction;

typedef struct _RequestSpiTransfer {
	pb_callback_t data;
} RequestSpiTransfer;

typedef struct _RequestSpiWrite {
	pb_callback_t data;
} RequestSpiWrite;

typedef struct _ResponseSpiRead {
	pb_callback_t data;
} ResponseSpiRead;

typedef struct _ResponseSpiTransfer {
	pb_callback_t data;
} ResponseSpiTransfer;

typedef struct _RequestDigitalRead {
	uint32_t pin;
} RequestDigitalRead;

typedef struct _RequestDigitalWrite {
	uint32_t pin;
	uint32_t value;
} RequestDigitalWrite;

typedef struct _RequestPinMode {
	uint32_t pin;
	PinMode mode;
} RequestPinMode;

typedef struct _RequestSpiRead {
	uint32_t length;
} RequestSpiRead;

typedef struct _ResponseDigitalRead {
	uint32_t value;
} ResponseDigitalRead;

typedef struct _ResponseSpiWrite {
	uint32_t length;
} ResponseSpiWrite;

typedef struct _SpiSettings {
	uint32_t speed;
	SpiSettings_ByteOrder byteOrder;
	SpiSettings_DataMode dataMode;
} SpiSettings;

typedef struct _RequestSpiBeginTransaction {
	bool has_settings;
	SpiSettings settings;
} RequestSpiBeginTransaction;

typedef struct _HostedCommand {
	HostedCommand_Version version;
	pb_size_t which_payload;
	union {
		RequestDigitalWrite requestDigitalWrite;
		RequestPinMode requestPinMode;
		RequestDigitalRead requestDigitalRead;
		ResponseDigitalRead responseDigitalRead;
		RequestSpiBeginTransaction requestSpiBeginTransaction;
		RequestSpiEndTransaction requestSpiEndTransaction;
		RequestSpiTransfer requestSpiTransfer;
		ResponseSpiTransfer responseSpiTransfer;
		RequestSpiWrite requestSpiWrite;
		ResponseSpiWrite responseSpiWrite;
		RequestSpiRead requestSpiRead;
		ResponseSpiRead responseSpiRead;
	} payload;
} HostedCommand;

/* Helper constants for enums */
#define _PinMode_MIN PinMode_INPUT
#define _PinMode_MAX PinMode_INPUT_PULLUP
#define _PinMode_ARRAYSIZE ((PinMode)(PinMode_INPUT_PULLUP + 1))

#define _SpiSettings_ByteOrder_MIN SpiSettings_ByteOrder_MSBFIRST
#define _SpiSettings_ByteOrder_MAX SpiSettings_ByteOrder_LSBFIRST
#define _SpiSettings_ByteOrder_ARRAYSIZE ((SpiSettings_ByteOrder)(SpiSettings_ByteOrder_LSBFIRST + 1))

#define _SpiSettings_DataMode_MIN SpiSettings_DataMode_SPI_MODE0
#define _SpiSettings_DataMode_MAX SpiSettings_DataMode_SPI_MODE3
#define _SpiSettings_DataMode_ARRAYSIZE ((SpiSettings_DataMode)(SpiSettings_DataMode_SPI_MODE3 + 1))

#define _HostedCommand_Version_MIN HostedCommand_Version_HOSTED_V_1_0
#define _HostedCommand_Version_MAX HostedCommand_Version_HOSTED_V_1_0
#define _HostedCommand_Version_ARRAYSIZE ((HostedCommand_Version)(HostedCommand_Version_HOSTED_V_1_0 + 1))

/* Initializer values for message structs */
#define RequestDigitalWrite_init_default                                                                               \
	{                                                                                                                  \
		0, 0                                                                                                           \
	}
#define RequestPinMode_init_default                                                                                    \
	{                                                                                                                  \
		0, _PinMode_MIN                                                                                                \
	}
#define RequestDigitalRead_init_default                                                                                \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define ResponseDigitalRead_init_default                                                                               \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define SpiSettings_init_default                                                                                       \
	{                                                                                                                  \
		0, _SpiSettings_ByteOrder_MIN, _SpiSettings_DataMode_MIN                                                       \
	}
#define RequestSpiBeginTransaction_init_default                                                                        \
	{                                                                                                                  \
		false, SpiSettings_init_default                                                                                \
	}
#define RequestSpiEndTransaction_init_default                                                                          \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define RequestSpiTransfer_init_default                                                                                \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define ResponseSpiTransfer_init_default                                                                               \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define RequestSpiWrite_init_default                                                                                   \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define ResponseSpiWrite_init_default                                                                                  \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define RequestSpiRead_init_default                                                                                    \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define ResponseSpiRead_init_default                                                                                   \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define HostedCommand_init_default                                                                                     \
	{                                                                                                                  \
		_HostedCommand_Version_MIN, 0,                                                                                 \
		{                                                                                                              \
			RequestDigitalWrite_init_default                                                                           \
		}                                                                                                              \
	}
#define RequestDigitalWrite_init_zero                                                                                  \
	{                                                                                                                  \
		0, 0                                                                                                           \
	}
#define RequestPinMode_init_zero                                                                                       \
	{                                                                                                                  \
		0, _PinMode_MIN                                                                                                \
	}
#define RequestDigitalRead_init_zero                                                                                   \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define ResponseDigitalRead_init_zero                                                                                  \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define SpiSettings_init_zero                                                                                          \
	{                                                                                                                  \
		0, _SpiSettings_ByteOrder_MIN, _SpiSettings_DataMode_MIN                                                       \
	}
#define RequestSpiBeginTransaction_init_zero                                                                           \
	{                                                                                                                  \
		false, SpiSettings_init_zero                                                                                   \
	}
#define RequestSpiEndTransaction_init_zero                                                                             \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define RequestSpiTransfer_init_zero                                                                                   \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define ResponseSpiTransfer_init_zero                                                                                  \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define RequestSpiWrite_init_zero                                                                                      \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define ResponseSpiWrite_init_zero                                                                                     \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define RequestSpiRead_init_zero                                                                                       \
	{                                                                                                                  \
		0                                                                                                              \
	}
#define ResponseSpiRead_init_zero                                                                                      \
	{                                                                                                                  \
		{                                                                                                              \
			{NULL}, NULL                                                                                               \
		}                                                                                                              \
	}
#define HostedCommand_init_zero                                                                                        \
	{                                                                                                                  \
		_HostedCommand_Version_MIN, 0,                                                                                 \
		{                                                                                                              \
			RequestDigitalWrite_init_zero                                                                              \
		}                                                                                                              \
	}

/* Field tags (for use in manual encoding/decoding) */
#define RequestSpiTransfer_data_tag 1
#define RequestSpiWrite_data_tag 1
#define ResponseSpiRead_data_tag 1
#define ResponseSpiTransfer_data_tag 1
#define RequestDigitalRead_pin_tag 1
#define RequestDigitalWrite_pin_tag 1
#define RequestDigitalWrite_value_tag 2
#define RequestPinMode_pin_tag 1
#define RequestPinMode_mode_tag 2
#define RequestSpiRead_length_tag 1
#define ResponseDigitalRead_value_tag 1
#define ResponseSpiWrite_length_tag 1
#define SpiSettings_speed_tag 1
#define SpiSettings_byteOrder_tag 2
#define SpiSettings_dataMode_tag 3
#define RequestSpiBeginTransaction_settings_tag 1
#define HostedCommand_version_tag 1
#define HostedCommand_requestDigitalWrite_tag 10
#define HostedCommand_requestPinMode_tag 11
#define HostedCommand_requestDigitalRead_tag 12
#define HostedCommand_responseDigitalRead_tag 13
#define HostedCommand_requestSpiBeginTransaction_tag 14
#define HostedCommand_requestSpiEndTransaction_tag 15
#define HostedCommand_requestSpiTransfer_tag 16
#define HostedCommand_responseSpiTransfer_tag 17
#define HostedCommand_requestSpiWrite_tag 18
#define HostedCommand_responseSpiWrite_tag 19
#define HostedCommand_requestSpiRead_tag 20
#define HostedCommand_responseSpiRead_tag 21

/* Struct field encoding specification for nanopb */
#define RequestDigitalWrite_FIELDLIST(X, a)                                                                            \
	X(a, STATIC, SINGULAR, UINT32, pin, 1)                                                                             \
	X(a, STATIC, SINGULAR, UINT32, value, 2)
#define RequestDigitalWrite_CALLBACK NULL
#define RequestDigitalWrite_DEFAULT NULL

#define RequestPinMode_FIELDLIST(X, a)                                                                                 \
	X(a, STATIC, SINGULAR, UINT32, pin, 1)                                                                             \
	X(a, STATIC, SINGULAR, UENUM, mode, 2)
#define RequestPinMode_CALLBACK NULL
#define RequestPinMode_DEFAULT NULL

#define RequestDigitalRead_FIELDLIST(X, a) X(a, STATIC, SINGULAR, UINT32, pin, 1)
#define RequestDigitalRead_CALLBACK NULL
#define RequestDigitalRead_DEFAULT NULL

#define ResponseDigitalRead_FIELDLIST(X, a) X(a, STATIC, SINGULAR, UINT32, value, 1)
#define ResponseDigitalRead_CALLBACK NULL
#define ResponseDigitalRead_DEFAULT NULL

#define SpiSettings_FIELDLIST(X, a)                                                                                    \
	X(a, STATIC, SINGULAR, UINT32, speed, 1)                                                                           \
	X(a, STATIC, SINGULAR, UENUM, byteOrder, 2)                                                                        \
	X(a, STATIC, SINGULAR, UENUM, dataMode, 3)
#define SpiSettings_CALLBACK NULL
#define SpiSettings_DEFAULT NULL

#define RequestSpiBeginTransaction_FIELDLIST(X, a) X(a, STATIC, OPTIONAL, MESSAGE, settings, 1)
#define RequestSpiBeginTransaction_CALLBACK NULL
#define RequestSpiBeginTransaction_DEFAULT NULL
#define RequestSpiBeginTransaction_settings_MSGTYPE SpiSettings

#define RequestSpiEndTransaction_FIELDLIST(X, a)

#define RequestSpiEndTransaction_CALLBACK NULL
#define RequestSpiEndTransaction_DEFAULT NULL

#define RequestSpiTransfer_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, data, 1)
#define RequestSpiTransfer_CALLBACK pb_default_field_callback
#define RequestSpiTransfer_DEFAULT NULL

#define ResponseSpiTransfer_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, data, 1)
#define ResponseSpiTransfer_CALLBACK pb_default_field_callback
#define ResponseSpiTransfer_DEFAULT NULL

#define RequestSpiWrite_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, data, 1)
#define RequestSpiWrite_CALLBACK pb_default_field_callback
#define RequestSpiWrite_DEFAULT NULL

#define ResponseSpiWrite_FIELDLIST(X, a) X(a, STATIC, SINGULAR, UINT32, length, 1)
#define ResponseSpiWrite_CALLBACK NULL
#define ResponseSpiWrite_DEFAULT NULL

#define RequestSpiRead_FIELDLIST(X, a) X(a, STATIC, SINGULAR, UINT32, length, 1)
#define RequestSpiRead_CALLBACK NULL
#define RequestSpiRead_DEFAULT NULL

#define ResponseSpiRead_FIELDLIST(X, a) X(a, CALLBACK, SINGULAR, BYTES, data, 1)
#define ResponseSpiRead_CALLBACK pb_default_field_callback
#define ResponseSpiRead_DEFAULT NULL

#define HostedCommand_FIELDLIST(X, a)                                                                                  \
	X(a, STATIC, SINGULAR, UENUM, version, 1)                                                                          \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestDigitalWrite, payload.requestDigitalWrite), 10)                      \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestPinMode, payload.requestPinMode), 11)                                \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestDigitalRead, payload.requestDigitalRead), 12)                        \
	X(a, STATIC, ONEOF, MESSAGE, (payload, responseDigitalRead, payload.responseDigitalRead), 13)                      \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestSpiBeginTransaction, payload.requestSpiBeginTransaction), 14)        \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestSpiEndTransaction, payload.requestSpiEndTransaction), 15)            \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestSpiTransfer, payload.requestSpiTransfer), 16)                        \
	X(a, STATIC, ONEOF, MESSAGE, (payload, responseSpiTransfer, payload.responseSpiTransfer), 17)                      \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestSpiWrite, payload.requestSpiWrite), 18)                              \
	X(a, STATIC, ONEOF, MESSAGE, (payload, responseSpiWrite, payload.responseSpiWrite), 19)                            \
	X(a, STATIC, ONEOF, MESSAGE, (payload, requestSpiRead, payload.requestSpiRead), 20)                                \
	X(a, STATIC, ONEOF, MESSAGE, (payload, responseSpiRead, payload.responseSpiRead), 21)
#define HostedCommand_CALLBACK NULL
#define HostedCommand_DEFAULT NULL
#define HostedCommand_payload_requestDigitalWrite_MSGTYPE RequestDigitalWrite
#define HostedCommand_payload_requestPinMode_MSGTYPE RequestPinMode
#define HostedCommand_payload_requestDigitalRead_MSGTYPE RequestDigitalRead
#define HostedCommand_payload_responseDigitalRead_MSGTYPE ResponseDigitalRead
#define HostedCommand_payload_requestSpiBeginTransaction_MSGTYPE RequestSpiBeginTransaction
#define HostedCommand_payload_requestSpiEndTransaction_MSGTYPE RequestSpiEndTransaction
#define HostedCommand_payload_requestSpiTransfer_MSGTYPE RequestSpiTransfer
#define HostedCommand_payload_responseSpiTransfer_MSGTYPE ResponseSpiTransfer
#define HostedCommand_payload_requestSpiWrite_MSGTYPE RequestSpiWrite
#define HostedCommand_payload_responseSpiWrite_MSGTYPE ResponseSpiWrite
#define HostedCommand_payload_requestSpiRead_MSGTYPE RequestSpiRead
#define HostedCommand_payload_responseSpiRead_MSGTYPE ResponseSpiRead

extern const pb_msgdesc_t RequestDigitalWrite_msg;
extern const pb_msgdesc_t RequestPinMode_msg;
extern const pb_msgdesc_t RequestDigitalRead_msg;
extern const pb_msgdesc_t ResponseDigitalRead_msg;
extern const pb_msgdesc_t SpiSettings_msg;
extern const pb_msgdesc_t RequestSpiBeginTransaction_msg;
extern const pb_msgdesc_t RequestSpiEndTransaction_msg;
extern const pb_msgdesc_t RequestSpiTransfer_msg;
extern const pb_msgdesc_t ResponseSpiTransfer_msg;
extern const pb_msgdesc_t RequestSpiWrite_msg;
extern const pb_msgdesc_t ResponseSpiWrite_msg;
extern const pb_msgdesc_t RequestSpiRead_msg;
extern const pb_msgdesc_t ResponseSpiRead_msg;
extern const pb_msgdesc_t HostedCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RequestDigitalWrite_fields &RequestDigitalWrite_msg
#define RequestPinMode_fields &RequestPinMode_msg
#define RequestDigitalRead_fields &RequestDigitalRead_msg
#define ResponseDigitalRead_fields &ResponseDigitalRead_msg
#define SpiSettings_fields &SpiSettings_msg
#define RequestSpiBeginTransaction_fields &RequestSpiBeginTransaction_msg
#define RequestSpiEndTransaction_fields &RequestSpiEndTransaction_msg
#define RequestSpiTransfer_fields &RequestSpiTransfer_msg
#define ResponseSpiTransfer_fields &ResponseSpiTransfer_msg
#define RequestSpiWrite_fields &RequestSpiWrite_msg
#define ResponseSpiWrite_fields &ResponseSpiWrite_msg
#define RequestSpiRead_fields &RequestSpiRead_msg
#define ResponseSpiRead_fields &ResponseSpiRead_msg
#define HostedCommand_fields &HostedCommand_msg

/* Maximum encoded size of messages (where known) */
#define RequestDigitalWrite_size 12
#define RequestPinMode_size 8
#define RequestDigitalRead_size 6
#define ResponseDigitalRead_size 6
#define SpiSettings_size 10
#define RequestSpiBeginTransaction_size 12
#define RequestSpiEndTransaction_size 0
/* RequestSpiTransfer_size depends on runtime parameters */
/* ResponseSpiTransfer_size depends on runtime parameters */
/* RequestSpiWrite_size depends on runtime parameters */
#define ResponseSpiWrite_size 6
#define RequestSpiRead_size 6
/* ResponseSpiRead_size depends on runtime parameters */
/* HostedCommand_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
