# => SMING

SPIFFS_SMING	:= $(ARCH_COMPONENTS)/spiffs
SPIFFS_BASE		:= $(COMPONENTS)/spiffs
SUBMODULES		+= $(SPIFFS_BASE)
MODULES			+= $(SPIFFS_SMING) $(SPIFFS_BASE)/src
EXTRA_INCDIR	+= $(SPIFFS_SMING) $(SPIFFS_BASE)/src





# => APP

CONFIG_VARS			+= DISABLE_SPIFFS SPIFF_BIN_OUT
DISABLE_SPIFFS		?= 0
SPIFF_BIN_OUT		?= spiff_rom
SPIFF_BIN_OUT		:= $(FW_BASE)/$(SPIFF_BIN_OUT).bin
EXTRA_INCDIR		+= $(ARCH_COMPONENTS)/spiffs $(COMPONENTS)/spiffs/src
CFLAGS				+= -DRBOOT_SPIFFS_0=$(RBOOT_SPIFFS_0)
CFLAGS				+= -DRBOOT_SPIFFS_1=$(RBOOT_SPIFFS_1)
CUSTOM_TARGETS		+= $(SPIFF_BIN_OUT)

