COMPONENT_SRCDIRS := \
	src \
	$(call ListAllSubDirs,$(COMPONENT_PATH)/src) \

COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS)


COMPONENT_DEPENDS := FlashString

COMPONENT_DOXYGEN_INPUT := src

COMPONENT_DOCFILES := \
	docs/*