ARDUINO_LIBRARIES := \
	SmingTest \
	SPI

#
HOST_NETWORK_OPTIONS := --nonet
DISABLE_NETWORK := 1
DEBUG_VERBOSE_LEVEL := 2

#
COMPONENT_VARS += SPISOFT_ENABLE
SPISOFT_ENABLE ?= 1
COMPONENT_CPPFLAGS += -DSPISOFT_ENABLE=$(SPISOFT_ENABLE)

#
COMPONENT_VARS += SPISOFT_CALIBRATE
SPISOFT_CALIBRATE ?= 0
COMPONENT_CPPFLAGS += -DSPISOFT_CALIBRATE=$(SPISOFT_CALIBRATE)

#
COMPONENT_VARS += CPU_FAST
CPU_FAST ?= 0
COMPONENT_CPPFLAGS += -DCPU_FAST=$(CPU_FAST)

.PHONY: execute
execute: flash run
