#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Sming Application

include $(IDF_PATH)/make/project.mk

Application.elf:
	echo "Done!"

