COMPONENT_INCDIRS := src/include
COMPONENT_SRCDIRS := src
COMPONENT_DOXYGEN_INPUT := src/include
COMPONENT_DOXYGEN_INCLUDE_PATH := src/include/config.hpp
COMPONENT_DOXYGEN_PREDEFINED := \
	FSTR_INLINE= \
	FSTR_PACKED=
