/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "cast_channel.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(extensions_api_cast_channel_CastMessage, extensions_api_cast_channel_CastMessage, AUTO)


PB_BIND(extensions_api_cast_channel_AuthChallenge, extensions_api_cast_channel_AuthChallenge, AUTO)


PB_BIND(extensions_api_cast_channel_AuthResponse, extensions_api_cast_channel_AuthResponse, AUTO)


PB_BIND(extensions_api_cast_channel_AuthError, extensions_api_cast_channel_AuthError, AUTO)


PB_BIND(extensions_api_cast_channel_DeviceAuthMessage, extensions_api_cast_channel_DeviceAuthMessage, AUTO)






