COMPONENT_DEPENDS := Hosted
ifneq ($(ENABLE_HOSTED),)
	COMPONENT_SRCDIRS += src/$(ENABLE_HOSTED) 
endif

COMPONENT_VARS := ENABLE_HOSTED HOSTED_SERVER_IP
COMPONENT_CFLAGS := -DHOSTED_SERVER_IP=$(HOSTED_SERVER_IP)
COMPONENT_CXXFLAGS := $(COMPONENT_CFLAGS)