#####################################################################
#### Please don't change this file. Use component.mk instead ####
#####################################################################

ifndef SMING_HOME
$(error SMING_HOME is not set. Please configure it as an environment variable)
endif

# Include application Makefile
include $(SMING_HOME)/project.mk
