COMPONENT_INCDIRS := src/include
COMPONENT_SRCDIRS := src

COMPONENT_VARS += SSDP_DEBUG_VERBOSE
SSDP_DEBUG_VERBOSE ?= 0
ifeq ($(SSDP_DEBUG_VERBOSE),1)
COMPONENT_CXXFLAGS += -DSSDP_DEBUG_VERBOSE=1
endif

