COMPONENT_SRCDIRS := \
	src \
	$(call ListAllSubDirs,$(COMPONENT_PATH)/src) \

COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS)

COMPONENT_DOXYGEN_INPUT := src

COMPONENT_DOCFILES := \
	docs/*


COMPONENT_VARS := CMDPROC_FLASHSTRINGS
ifeq ($(CMDPROC_FLASHSTRINGS),1)
GLOBAL_CFLAGS += -DCMDPROC_FLASHSTRINGS
endif
