COMPONENT_SUBMODULES := modbusino
COMPONENT_SRCDIRS := modbusino
COMPONENT_INCDIRS := modbusino

COMPONENT_VARS += RS485_RE_PIN
RS485_RE_PIN ?= 15
COMPONENT_CXXFLAGS += -DRS485_RE_PIN=$(RS485_RE_PIN)

COMPONENT_VARS += RS485_TX_LEVEL
RS485_TX_LEVEL ?= HIGH
COMPONENT_CXXFLAGS += -DRS485_TX_LEVEL=$(RS485_TX_LEVEL)

COMPONENT_VARS += MB_PRE_TX_DELAY
MB_PRE_TX_DELAY ?= 100
COMPONENT_CXXFLAGS += -DMB_PRE_TX_DELAY=$(MB_PRE_TX_DELAY)

COMPONENT_VARS += MB_POST_TX_DELAY
MB_POST_TX_DELAY ?= 1000
COMPONENT_CXXFLAGS += -DMB_POST_TX_DELAY=$(MB_POST_TX_DELAY)
