COMPONENT_SUBMODULES := modbusino
COMPONENT_SRCDIRS := modbusino
COMPONENT_INCDIRS := modbusino

COMPONENT_VARS += RS485_RE_PIN
RS485_RE_PIN ?= 15
COMPONENT_CXXFLAGS := -DRS485_RE_PIN=$(RS485_RE_PIN)

COMPONENT_VARS += RS485_TX_LEVEL
RS485_TX_LEVEL ?= HIGH
COMPONENT_CXXFLAGS := -DRS485_TX_LEVEL=$(RS485_TX_LEVEL)
