COMPONENT_SRCDIRS := \
	src \
	src/Arch/$(SMING_ARCH)

COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS)

#
COMPONENT_RELINK_VARS := ENABLE_SPISOFT_DELAY
ENABLE_SPISOFT_DELAY ?= 0
ifeq ($(ENABLE_SPISOFT_DELAY),1)
COMPONENT_CPPFLAGS := -DENABLE_SPISOFT_DELAY=1
endif

#
COMPONENT_VARS += ENABLE_SPI_DEBUG
ENABLE_SPI_DEBUG ?= 0
ifeq ($(ENABLE_SPI_DEBUG),1)
GLOBAL_CFLAGS += -DSPI_DEBUG=1
endif
