COMPONENT_SRCDIRS	:= src
COMPONENT_INCDIRS	:= src/include

COMPONENT_DOXYGEN_INPUT := src/include

COMPONENT_VARS		+= ENABLE_CUSTOM_LWIP

# If using Espressif LWIP...
ifeq ($(ENABLE_CUSTOM_LWIP),0)
ENABLE_ESPCONN		:= 1
GLOBAL_CFLAGS		+= -DENABLE_ESPCONN
endif

GLOBAL_CFLAGS		+= -DENABLE_CUSTOM_LWIP=$(ENABLE_CUSTOM_LWIP)
