COMPONENT_SUBMODULES := ESP32-BLE-Gamepad
COMPONENT_DEPENDS := NimBLE

COMPONENT_SRCDIRS := ESP32-BLE-Gamepad
COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS)

COMPONENT_CPPFLAGS:= -DUSE_NIMBLE=1
APP_CFLAGS += -DUSE_NIMBLE=1

COMPONENT_CXXFLAGS := -Wno-unused-parameter
