COMPONENT_SUBMODULES := ESP32-BLE-Gamepad
# TODO: Add later support for the other Esp32 variants
COMPONENT_SOC := esp32
COMPONENT_DEPENDS := NimBLE

COMPONENT_SRCDIRS := ESP32-BLE-Gamepad
COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS)

COMPONENT_CPPFLAGS:= -DUSE_NIMBLE=1
APP_CFLAGS += -DUSE_NIMBLE=1
