COMPONENT_SOC := host
COMPONENT_SRCDIRS := $(COMPONENT_PATH)/src
COMPONENT_DEPENDS := Hosted


COMPONENT_VARS += ENABLE_HOSTED_DIGITAL
ENABLE_HOSTED_DIGITAL ?= 1
COMPONENT_CPPFLAGS  += -DENABLE_HOSTED_DIGITAL=$(ENABLE_HOSTED_DIGITAL)

COMPONENT_VARS += ENABLE_HOSTED_WIRE
ENABLE_HOSTED_WIRE ?= 1
COMPONENT_CPPFLAGS  += -DENABLE_HOSTED_WIRE=$(ENABLE_HOSTED_WIRE)
