COMPONENT_SRCDIRS := $(COMPONENT_PATH)/src
COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS) $(COMPONENT_PATH)/include 
COMPONENT_DEPENDS := rpc

# Architecture of the device where the hosted service will be flashed
HOSTED_ARCH ?= Esp8266

HOSTED_APP_DIR := $(COMPONENT_PATH)/app

RELINK_VARS := ENABLE_HOSTED

COMPONENT_VARS := ENABLE_HOSTED
ENABLE_HOSTED ?=

ifneq ($(ENABLE_HOSTED),)
	COMPONENT_SRCDIRS += $(COMPONENT_PATH)/init/$(ENABLE_HOSTED) 
endif

COMPONENT_VARS += HOSTED_SERVER_IP

COMPONENT_CFLAGS := -DHOSTED_SERVER_IP=$(HOSTED_SERVER_IP)
COMPONENT_CXXFLAGS := $(COMPONENT_CFLAGS)
