COMPONENT_SRCDIRS := $(COMPONENT_PATH)/src
COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS) $(COMPONENT_PATH)/include 
COMPONENT_DEPENDS := simpleRPC

# Architecture of the device where the hosted service will be flashed
HOSTED_ARCH ?= Esp8266

COMPONENT_RELINK_VARS += ENABLE_HOSTED
COMPONENT_VARS := ENABLE_HOSTED

ENABLE_HOSTED ?=

ifneq ($(ENABLE_HOSTED),)
	COMPONENT_SRCDIRS += $(COMPONENT_PATH)/init/$(ENABLE_HOSTED) 
	EXTRA_LDFLAGS := -Wl,-wrap,host_init
	COMPONENT_DEPENDS += seriallib
endif

COMPONENT_VARS += HOSTED_SERVER_IP

COMPONENT_VARS += HOSTED_COM_PORT
HOSTED_COM_PORT := "/dev/ttyUSB0"
ifneq ($(COM_PORT),)
	HOSTED_COM_PORT:=$(COM_PORT)
endif

COMPONENT_VARS += HOSTED_COM_SPEED
HOSTED_COM_SPEED := 115200

COMPONENT_CFLAGS = -DHOSTED_SERVER_IP=$(HOSTED_SERVER_IP) -DHOSTED_COM_PORT="\"$(HOSTED_COM_PORT)"\" -DHOSTED_COM_SPEED=$(HOSTED_COM_SPEED)
COMPONENT_CXXFLAGS := $(COMPONENT_CFLAGS)
