COMPONENT_SUBMODULES	+= simpleRPC

SIMPLE_RPC_ROOT := $(COMPONENT_PATH)/simpleRPC

COMPONENT_SRCDIRS := $(SIMPLE_RPC_ROOT)/src $(COMPONENT_PATH)/src
COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS) $(COMPONENT_PATH)/include
