var modules =
[
    [ "AtCommand serial", "group__serial.html", "group__serial" ],
    [ "Command Handler", "group__commandhandler.html", "group__commandhandler" ],
    [ "Configuration", "group__Configuration.html", "group__Configuration" ],
    [ "Core API", "group__CoreAPI.html", "group__CoreAPI" ],
    [ "Date and time functions", "group__datetime.html", "group__datetime" ],
    [ "Debug functions", "group__debug.html", "group__debug" ],
    [ "Delegate", "group__delegate.html", "group__delegate" ],
    [ "File system", "group__filesystem.html", "group__filesystem" ],
    [ "GPIO functions", "group__gpio.html", "group__gpio" ],
    [ "Get Started", "group__GetStarted.html", null ],
    [ "Hardware PWM functions", "group__hw__pwm.html", "group__hw__pwm" ],
    [ "Hardware timer", "group__hwtimer.html", "group__hwtimer" ],
    [ "Interrupt functions", "group__interrupts.html", "group__interrupts" ],
    [ "Libraries", "group__libraries.html", "group__libraries" ],
    [ "Networking", "group__networking.html", "group__networking" ],
    [ "Nextion Component", "group__Component.html", "group__Component" ],
    [ "Print stream functions", "group__print.html", "group__print" ],
    [ "RC Servo functions", "group__Servo.html", "group__Servo" ],
    [ "SPI Hardware support", "group__hw__spi.html", "group__hw__spi" ],
    [ "SPI support classes", "group__base__spi.html", "group__base__spi" ],
    [ "Sming constant values", "group__constants.html", "group__constants" ],
    [ "Sming event handlers", "group__event__handlers.html", "group__event__handlers" ],
    [ "Sming structures", "group__structures.html", "group__structures" ],
    [ "Stream functions", "group__stream.html", "group__stream" ],
    [ "System", "group__system.html", "group__system" ],
    [ "Timer functions", "group__timer.html", "group__timer" ],
    [ "Watchdog Timer", "group__wdt.html", "group__wdt" ],
    [ "Websocket Frame", "group__wsframe.html", "group__wsframe" ],
    [ "WiFi Access Point", "group__wifi__ap.html", "group__wifi__ap" ],
    [ "WiFi Station Interface", "group__wifi__sta.html", "group__wifi__sta" ]
];