name: Continuous Integration (CI) for Esp32

on:
  push:
  
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        variant: [esp32, esp32s2, esp32c3, esp32s3, esp32c2]
        idf_version: ["4.4", "5.0", "5.2"]
        include:
          - os: ubuntu-latest
            variant: esp32
            idf_version: "4.3"
        exclude:
          - variant: esp32c2
            idf_version: "4.4"
          - os: macos-latest
            idf_version: "4.4"
          - os: macos-latest
            idf_version: "5.0"
          - os: windows-latest
            idf_version: "5.0"

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ toJson(matrix) }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}

    env:
      SMING_ARCH: Esp32
      SMING_SOC: ${{ matrix.variant }}
      INSTALL_IDF_VER: ${{ matrix.idf_version }}
      ENABLE_CCACHE: 1

    steps:
    - name: Fix autocrlf setting
      run: |
        git config --global --add core.autocrlf input

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.idf_version == '4.3' && '3.8' || '3.12' }}

    - name: Configure environment
      shell: pwsh
      run: |
        "CI_BUILD_DIR=" + (Resolve-Path ".").path >> $env:GITHUB_ENV
        "SMING_HOME=" + (Resolve-Path "Sming").path >> $env:GITHUB_ENV

    - name: Fix permissions
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        sudo chown $USER /opt

    - name: Cache ESP-IDF and build tools
      uses: actions/cache@v4
      with:
        path: |
          /opt/esp-idf-${{ matrix.idf_version }}
          /opt/esp32
        key: ${{ matrix.os }}-idf-${{ matrix.idf_version }}

    - name: Install build tools for Ubuntu / MacOS
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        Tools/ci/install.sh

    - name: Install build tools for Windows   
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
         . Tools/ci/setenv.ps1
         Tools/ci/install.cmd

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ matrix.variant }}-${{ matrix.idf_version }}

    - name: Build and test for ${{matrix.variant}} with IDF v${{matrix.idf_version}} on Ubuntu / MacOS
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        source $SMING_HOME/../Tools/export.sh
        Tools/ci/build.sh

    - name: Build and test for ${{matrix.variant}} with IDF v${{matrix.idf_version}} on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        . Tools/ci/setenv.ps1
        Tools/ci/build.cmd
