name: Continuous Integration (CI)

on:
  workflow_call:
    inputs:
      sming_repo:
        description: 'Full URL for Sming repository'
        default: 'https://github.com/SmingHub/Sming'
        type: string
      sming_branch:
        description: 'Sming branch to run against'
        default: 'develop'
        type: string
      alias:
        description: 'Library alias'
        default: ''
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        variant: [esp8266, host, esp32, esp32s2, esp32c3, esp32s3, esp32c2, rp2040]
        idf_version: ["4.4", ""] # "" denotes default, currently 5.2
        include:
          - variant: esp8266
            arch: Esp8266
          - variant: host
            arch: Host
          - variant: esp32
            arch: Esp32
          - variant: esp32s2
            arch: Esp32
          - variant: esp32c3
            arch: Esp32
          - variant: esp32s3
            arch: Esp32
          - variant: esp32c2
            arch: Esp32
          - variant: rp2040
            arch: Rp2040
        exclude:
          - variant: esp32c2
            idf_version: "4.4"
          - variant: esp8266
            idf_version: "4.4"
          - variant: host
            idf_version: "4.4"
          - variant: rp2040
            idf_version: "4.4"

    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-${{ toJson(matrix) }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}

    env:
      SMING_ARCH: ${{ matrix.arch }}
      SMING_SOC: ${{ matrix.variant }}
      INSTALL_IDF_VER: ${{ matrix.idf_version }}

    steps:
    - name: Fix autocrlf setting
      run: |
        git config --global --add core.autocrlf input

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Create library alias
      if: ${{ inputs.alias }}
      shell: pwsh
      run: |
        New-Item -ItemType SymbolicLink -Path "../${{ inputs.alias }}" -Target (Resolve-Path ".").path

    - name: Checkout sming
      run: |
        git clone ${{ inputs.sming_repo }} -b ${{ inputs.sming_branch }} --depth 1 ../../sming

    - name: Configure environment
      shell: pwsh
      run: |
        "SMING_HOME=" + (Resolve-Path "../../sming/Sming").path >> $env:GITHUB_ENV
        "COMPONENT_SEARCH_DIRS=" + (Resolve-Path "..").path >> $env:GITHUB_ENV
        "CI_MAKEFILE=" + (Resolve-Path "../../sming/Tools/ci/library/Makefile") >> $env:GITHUB_ENV

    - name: Install build tools for Ubuntu
      if: ${{ matrix.os ==  'ubuntu-latest' }}
      run: |
        $SMING_HOME/../Tools/ci/install.sh

    - name: Install build tools for Windows   
      if: ${{ matrix.os ==  'windows-latest' }}
      run: |
        cd $env:SMING_HOME/..
        . Tools/ci/setenv.ps1
        Tools/ci/install.cmd

    - name: Build and Test for ${{matrix.arch}} on Ubuntu
      env:
        CLANG_FORMAT: clang-format-8
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        source $SMING_HOME/../Tools/export.sh
        make -j$(nproc) -f $CI_MAKEFILE

    - name: Build and Test for ${{matrix.arch}} on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        . "$env:SMING_HOME/../Tools/ci/setenv.ps1"
        make -j $env:NUMBER_OF_PROCESSORS -f $env:CI_MAKEFILE
